version: '3.3'

services:
  classdatabase:
    build:
      context: ./ClassDB
    container_name: classdatabase
    hostname: classdatabase
    networks:
     - class
    ports:
      - 9109:9109
    volumes:
      - my_sql:/var/lib/mysql
    environment:
      MYSQL_HOST: host.docker.internal
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: class_database
      MYSQL_DATABASE: classes_db
    deploy:
      restart_policy:
        condition: on-failure
  classfrontend:
    depends_on:
      - classmanagement
    build:
      context: ./Frontend
    container_name: classfrontend
    ports:
      - 9100:80
    environment:
      - NGINX_PORT=80
    
  classmanagement:
    depends_on: 
      - classdatabase
    build:
      context: ./Backend
    container_name: classmanagement
    hostname: classmanagement
    networks:
      - class
    ports:
      - 9101:9101
  

volumes:
  my_sql:

networks:
  class:
    driver: bridge 